# Generated by Django 5.1.2 on 2024-10-10 10:39

import django.db.models.deletion
import profileUser.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user1', to=settings.AUTH_USER_MODEL, to_field='nickname')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user2', to=settings.AUTH_USER_MODEL, to_field='nickname')),
            ],
            managers=[
                ('objects', profileUser.managers.ChatManager()),
            ],
        ),
    ]
