# Generated by Django 5.1.2 on 2024-10-10 13:41

import django.db.models.deletion
import profileUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileUser', '0002_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('uid_Chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileUser.chat')),
            ],
            managers=[
                ('objects', profileUser.models.MessageChat()),
            ],
        ),
    ]
